import moment from 'moment'

export const taskActions = {
  GET_TASK: 0,
  UPDATE_TASK: 1,
}

export const appActions = {
  GO_TO_PREVIOUS_WEEK: 0,
  GO_TO_NEXT_WEEK: 1,
  GET_TASKS: 2,
  DELETE_TASK: 3,
  CREATE_TASK: 4,
  UPDATE_TASK: 5,
  CHANGE_DARK_MODE: 6,
  GET_USER_DATA: 7,
  CREATE_HABIT: 8,
  DELETE_HABIT: 9,
  UPDATE_HABIT: 10,
  SHOW_LOGIN_SCREEN: 11,
  CHANGE_LOADING: 12,
  GET_INITIAL_DATA: 13,
}

export const GENERIC_ERROR_MESSAGE = 'An error occured, please try again later.'

export const INITIAL_TASKS = [
  {
    color: 'indigo',
    highPriority: false,
    completed: false,
    isToDo: false,
    _id: '1',
    name: 'Welcome to Weekly Planner!',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'silver',
    highPriority: false,
    completed: false,
    isToDo: false,
    _id: '2',
    name: 'Here you can plan your weeks',
    userId: 0,
    date: moment().startOf('isoWeek').add(1, 'd'),
  },
  {
    color: 'red',
    highPriority: true,
    completed: false,
    isToDo: false,
    _id: '3',
    name: 'I am a high priority task',
    userId: 0,
    date: moment().startOf('isoWeek').add(3, 'd'),
  },
  {
    color: 'teal',
    highPriority: false,
    completed: true,
    isToDo: false,
    _id: '4',
    name: 'I am a completed task .. yeey',
    userId: 0,
    date: moment().startOf('isoWeek').add(3, 'd'),
  },
  {
    color: 'yellow',
    highPriority: false,
    completed: true,
    isToDo: true,
    _id: '5',
    name: 'Here you can track your to-do list',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'red',
    highPriority: false,
    completed: true,
    isToDo: true,
    _id: '6',
    name: 'click on empty to add a task (focus input)',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'red',
    highPriority: false,
    completed: true,
    isToDo: true,
    _id: '7',
    name: 'add Github link',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'teal',
    highPriority: true,
    completed: true,
    isToDo: true,
    _id: '8',
    name: 'add option to change date format',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'teal',
    highPriority: true,
    completed: false,
    isToDo: true,
    _id: '9',
    name: 'navigate weeks using arrow keys',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'silver',
    highPriority: true,
    completed: true,
    isToDo: true,
    _id: '11',
    name: 'error handling and custom alerts',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
  {
    color: 'silver',
    highPriority: false,
    completed: false,
    isToDo: true,
    _id: '10',
    name: 'add new sign in providers',
    userId: 0,
    date: moment().startOf('isoWeek'),
  },
]
